### ISSUE TITLE
Bad spanish translation in attachment facturae

### ISSUE THREAD

**Issue by hydrosIII** [odoo-mexico/odoo-mexico#5]
In file  odoo-mexico/l10n_mx_ir_attachment_facturae/i18n/es.po
It should read Enviar al ciente in Sent Customer String.

**Comment by nhomar** [comment]
Hello.

This repository is not mantained yet, can you redirect you translation efforts on Version 7.0 to:

https://launchad.net/openerp-mexico-localization.

Thanks.
